### ISSUE TITLE
Падает на черном драконе

### ISSUE THREAD

**Issue by alekseik1** [DariaPetrovaa/The_game_arithmetic_dragons#2]
Стектрейс:
```bash
(base) ➜  The_game_arithmetic_dragons git:(master) ✗ python main.py
__main__
Добро пожаловать в арифметико-ролевую игру с драконами!
Представьтесь, пожалуйста: asd
У Вас на пути 3 драконов!
Вышел чёрный дракон!
Вопрос: 49*56
Ответ:2240
Ошибка!
** вам нанесён удар... **
Вопрос: 16*99
Ответ:1584
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    start_game()
  File "/private/tmp/The_game_arithmetic_dragons/tournament.py", line 50, in start_game
    game_tournament(hero, dragon_list)
  File "/private/tmp/The_game_arithmetic_dragons/tournament.py", line 24, in game_tournament
    hero.attack(dragon)
  File "/private/tmp/The_game_arithmetic_dragons/hero.py", line 13, in attack
    target._healh = target._heath - self._attack
AttributeError: 'BlackDragon' object has no attribute '_heath'
```

**Comment by alekseik1** [comment]
Утверждается, что профикшено в 39439b520e4edf6227ce15b6844ea0338f4d2c3d
